### ISSUE TITLE
Avoid using names like BG

### ISSUE THREAD

**Issue by dadkins20** [CKwan-hub/JSButtonHW#1]
https://github.com/CKwan-hub/JSButtonHW/blob/ed3013ec80b9e9e19f6e3e4e8dffb169db35f3c3/TimerHW.htm#L147

In general, I'd avoid using generic names like BG.  To another developer (like me) it's not intuitive what that is.  Alway try to be descriptive.  Other than that, good work.

**Comment by CKwan-hub** [comment]
Thank you for the feedback, I hope things (other than generic names) are
looking more streamlined, I used the notes of pointers from the project
when reviewing before upload. I will change the generic classes and ID's
and resubmit.
